### ISSUE TITLE
Evaluate not computing ranges with recent update (vo.7.11)

### ISSUE THREAD

**Issue by carbonNine** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#198]
Ever since the latest 0.7.11 update the value range in each of the selected attribute remains as `#-#`.
I have tried setting +/- 20% etc. of the current item (suffix/prefix) value but none of it works.

Not sure if this is related but every time the dialog opens for the item stats/search there is this entry in `main.log`:
```
[2021-04-23 21:05:04.328] [warn] {
  stack: "Error: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.\n" +
    '    at e.get (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.2c7d3fc6db56d2474380.js:1:33524616)\n' +
    '    at file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.2c7d3fc6db56d2474380.js:1:33526209\n' +
    '    at a.project (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.2c7d3fc6db56d2474380.js:1:33508061)\n' +
    '    at a._tryNext (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.2c7d3fc6db56d2474380.js:1:32440982)\n' +
    '    at a._next (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.2c7d3fc6db56d2474380.js:1:32440884)\n' +
    '    at a.next (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.2c7d3fc6db56d2474380.js:1:32428995)\n' +
    '    at a.notifyNext (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.2c7d3fc6db56d2474380.js:1:32441419)\n' +
    '    at a._next (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.2c7d3fc6db56d2474380.js:1:32436168)\n' +
    '    at a.next (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.2c7d3fc6db56d2474380.js:1:32428995)\n' +
    '    at e._subscribe (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.2c7d3fc6db56d2474380.js:1:32436485)'
}
```

**Comment by WhiteFang5** [comment]
Can you please provide a copy-paste of an example item you're trying to evaluate and which stats or attributes remain incorrect/bugged for you?

**Comment by carbonNine** [comment]
Sorry for the late reply.

I have managed to workaround this issue.

I came across similar such issues being reported in 'Awakened PoE Trade' repo.
Ref:
https://github.com/SnosMe/awakened-poe-trade/issues/346
https://github.com/SnosMe/awakened-poe-trade/issues/351

Basically since 3.14 item descriptions can have advanced mod description. However if one changes the 'Highlight Items and objects' keybinding from the default assignment to a custom binding it seems to impact the evaluate logic in the overlay. (I had a custom binding). Once restored to default all was well.

IMO this is still an issue in that one is not able to have custom key binding set for 'Highlight Items' alongside PoE Overlay. Whether this is a GGG client issue or Overlay one I know not.

HTH!

**Comment by WhiteFang5** [comment]
This issue has been fixes and will be shipped in the next release.
