### ISSUE TITLE
Ctrl+D never works

### ISSUE THREAD

**Issue by orlp** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#84]
When using Ctrl+D on an item to price check it always simply says "An Error Occurred" instead of the price, and the following error is in the log:

```
[2020-06-22 14:38:31.659] [warn] TypeError: Cannot read property 'id' of undefined
    at file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.82dd510b23ec29c19749.js:1:18197913
    at Array.map (<anonymous>)
    at a.project (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.82dd510b23ec29c19749.js:1:18197846)
    at a._tryNext (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.82dd510b23ec29c19749.js:1:17081057)
    at a._next (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.82dd510b23ec29c19749.js:1:17080959)
    at a.next (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.82dd510b23ec29c19749.js:1:17069070)
    at a.notifyNext (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.82dd510b23ec29c19749.js:1:17081494)
    at a._next (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.82dd510b23ec29c19749.js:1:17076243)
    at a.next (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.82dd510b23ec29c19749.js:1:17069070)
    at a.notifyNext (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.82dd510b23ec29c19749.js:1:17081494)
```

Using version 0.7.1.

Uninstalling, manually removing `%appdata\roaming\poe-overlay` and reinstalling did not fix the issue.

**Comment by null77** [comment]
+1

**Comment by andersxo** [comment]
+1

**Comment by rstrohmh** [comment]
Ditto.

**Comment by WhiteFang5** [comment]
I've encounted this error before. To resolve this, you have to open your settings, go to the evaluate section and check/change your evaluate currencies. I've just opened the drop-down, selected and then deselected a random currency and clicked save.

**Comment by C0rn3j** [comment]
Guys, don't post +1, use the reactions, that's what they're there for.

Same on Linux
```
22:47:10.068 › TypeError: Cannot read property 'id' of undefined
    at http://localhost:4200/main.js:15997:81
    at Array.map (<anonymous>)
    at MergeMapSubscriber.project (http://localhost:4200/main.js:15996:226)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext (http://localhost:4200/vendor.js:164916:27)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next (http://localhost:4200/vendor.js:164906:18)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (http://localhost:4200/vendor.js:159605:18)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/map.js.MapSubscriber._next (http://localhost:4200/vendor.js:164655:26)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (http://localhost:4200/vendor.js:159605:18)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/map.js.MapSubscriber._next (http://localhost:4200/vendor.js:164655:26)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (http://localhost:4200/vendor.js:159605:18)
22:47:16.824 › TypeError: Cannot read property 'id' of undefined
    at http://localhost:4200/main.js:15997:81
    at Array.map (<anonymous>)
    at MergeMapSubscriber.project (http://localhost:4200/main.js:15996:226)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext (http://localhost:4200/vendor.js:164916:27)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next (http://localhost:4200/vendor.js:164906:18)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (http://localhost:4200/vendor.js:159605:18)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/map.js.MapSubscriber._next (http://localhost:4200/vendor.js:164655:26)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (http://localhost:4200/vendor.js:159605:18)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/map.js.MapSubscriber._next (http://localhost:4200/vendor.js:164655:26)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (http://localhost:4200/vendor.js:159605:18)
22:48:35.993 › TypeError: Cannot read property 'id' of undefined
    at http://localhost:4200/main.js:16244:88
    at Array.map (<anonymous>)
    at MergeMapSubscriber.project (http://localhost:4200/main.js:16243:85)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext (http://localhost:4200/vendor.js:164916:27)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next (http://localhost:4200/vendor.js:164906:18)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (http://localhost:4200/vendor.js:159605:18)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber.notifyNext (http://localhost:4200/vendor.js:164942:26)
    at InnerSubscriber.push../node_modules/rxjs/_esm5/internal/InnerSubscriber.js.InnerSubscriber._next (http://localhost:4200/vendor.js:158818:21)
    at InnerSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (http://localhost:4200/vendor.js:159605:18)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber.notifyNext (http://localhost:4200/vendor.js:164942:26)
```
